### ISSUE TITLE
Página Home

### ISSUE THREAD

**Issue by brunnovaz1** [brunnovaz1/projetoADS#19]
Inserir um calendário com eventos marcados.
perguntas frequentes vai pro menu - ajuda
aumentar calendario
trocar imagem biblio por icone - menu
aumentar tamanho calendario

**Comment by Larysmo** [comment]
Concluída home

**Comment by brunnovaz1** [comment]
commit: ad3146d839169cd362f9fbc66b69aa9036fe3e42

**Comment by brunnovaz1** [comment]
commit: c0d8504a04252365933784220acdbdb352e741f0
